import {
  IconAlertTriangle,
  IconArrowRight,
  IconBell,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconBrandGoogle,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBox,
  // Icônes spécifiques trading/cashback
  IconArrowsExchange,
  IconBuildingBank,
  IconWallet,
  IconSparkles,
  IconGift,
  IconReceipt,
  IconLogout
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // Navigation principale
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  logout: IconLogout,
  close: IconX,
  product: IconBox,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  google: IconBrandGoogle,
  twitter: IconBrandTwitter,
  check: IconCheck,
  workspace: IconFolder,
  teams: IconUsers,
  pro: IconCrown,
  exclusive: IconStar,
  account: IconUserCircle,
  profile: IconUser,
  bell: IconBell,

  // Icônes spécifiques RendR Cashback
  transactions: IconArrowsExchange, // Échanges / Trades
  brokers: IconBuildingBank, // Institutions financières
  withdrawals: IconWallet, // Portefeuille / Retraits
  referral: IconGift, // Cadeau / Parrainage
  updates: IconSparkles, // Nouveautés
  receipt: IconReceipt // Historique
};
